[build]
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "panel_lavalle.html"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
